[package]
name = "chat"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.44.0"
tokio-stream = "0.1.17"
uuid = "1.15.1"
warp = "0.3.7"
